import type { ReactPodTrack } from "@/components/ReactPod";

export const REACT_POD_DEMO_TRACKS = [
  {
    id: "icy",
    title: "ICY",
    artist: "ITZY (있지)",
    album: "IT'z ICY",
    duration: 191.269,
    src: "/reactpod/audio/itzy/icy.mp3",
    artworkSrc: "/reactpod/covers/itzy/itz-icy.jpg",
    artworkAlt: "IT'z ICY album cover",
  },
  {
    id: "loco",
    title: "LOCO",
    artist: "ITZY (있지)",
    album: "CRAZY IN LOVE",
    duration: 191.53,
    src: "/reactpod/audio/itzy/loco.mp3",
    artworkSrc: "/reactpod/covers/itzy/crazy-in-love.jpg",
    artworkAlt: "CRAZY IN LOVE album cover",
  },
  {
    id: "not-shy",
    title: "Not Shy",
    artist: "ITZY (있지)",
    album: "Not Shy",
    duration: 177.946,
    src: "/reactpod/audio/itzy/not-shy.mp3",
    artworkSrc: "/reactpod/covers/itzy/not-shy.jpg",
    artworkAlt: "Not Shy album cover",
  },
  {
    id: "sorry-not-sorry",
    title: "Sorry Not Sorry",
    artist: "ITZY (있지)",
    album: "GUESS WHO",
    duration: 189.858,
    src: "/reactpod/audio/itzy/sorry-not-sorry.mp3",
    artworkSrc: "/reactpod/covers/itzy/guess-who.jpg",
    artworkAlt: "GUESS WHO album cover",
  },
  {
    id: "wannabe",
    title: "WANNABE",
    artist: "ITZY (있지)",
    album: "IT'z ME",
    duration: 191.347,
    src: "/reactpod/audio/itzy/wannabe.mp3",
    artworkSrc: "/reactpod/covers/itzy/itz-me.jpg",
    artworkAlt: "IT'z ME album cover",
  },
  {
    id: "dalla-dalla",
    title: "달라달라",
    artist: "ITZY (있지)",
    album: "IT'z Different",
    duration: 199.993,
    src: "/reactpod/audio/itzy/dalla-dalla.mp3",
    artworkSrc: "/reactpod/covers/itzy/itz-different.jpg",
    artworkAlt: "IT'z Different album cover",
  },
] satisfies readonly ReactPodTrack[];
